# Load required packages
library(shiny)
library(shinyjs)
library(tidyverse)
library(lubridate)
library(readxl)
library(forecast)
library(tseries)
library(lmtest)
library(plotly)
library(ggplot2)
library(DT)
library(scales)
library(glue)
library(stringr)
library(purrr)

cat("Packages loaded at:", format(Sys.time()), "\n")